### ISSUE TITLE
Please consider explicitly marking this modules as abandoned, if it is

### ISSUE THREAD

**Issue by y** [fxn/algorithm-combinatorics#1]
The last releases was in 2012 and none of the bugs have even garnered a response, so if you have no interest in maintaining your frequently-used module, please mark it as abandoned on PAUSE as described in this post:
http://blogs.perl.org/users/brian_d_foy/2013/02/mark-your-modules-as-adoptable-if-you-dont-want-them.html

**Comment by fxn** [comment]
Thanks for raising this issue, and thanks for the pointer to that procedure.

I have transferred maintairneship of all my modules to `ADOPTME`, and announced I am freeing them in the `module-authors` mailing list.
